name: "Build Docker image and publish to Docker Hub"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      repo:
        description: "Docker hub org and repository name"
        required: false
        default: "nethermindeth/tx-fuzz"
      tag:
        description: "Tag for the docker image"
        required: false
        default: "latest"
      dockerfile:
        description: "Dockerfile to use"
        required: false
        default: "Dockerfile"

jobs:
  build-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Settings
        id: settings
        run: |
          echo ::set-output name=docker_username::${{ secrets.DOCKER_USERNAME }}
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo ::set-output name=docker_image::nethermindeth/tx-fuzz
            echo ::set-output name=dockerfile::Dockerfile
            echo ::set-output name=TAG::latest
          else
            echo ::set-output name=docker_image::${{ github.event.inputs.repo }}
            echo ::set-output name=dockerfile::${{ github.event.inputs.dockerfile }}
            echo ::set-output name=TAG::${{ github.event.inputs.tag }}
          fi
      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Logging to Docker Hub
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.settings.outputs.docker_username }}" --password-stdin
      - name: Building image
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 -t "${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.TAG }}" -f ${{ steps.settings.outputs.dockerfile }} .
      - name: Pushing image to Docker Hub
        run: |
          docker push "${{ steps.settings.outputs.docker_image }}:latest"
          docker push "${{ steps.settings.outputs.docker_image }}:${{ steps.settings.outputs.TAG }}"
      - name: Clearing
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
